### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by clarkxl** [lkwq007/stablediffusion-infinity#150]
**Describe the bug**
Throws an error whenever I try to start it
**To Reproduce**
1. Install SD-infinity
2. Try to start it
3. Have it fail (tbh idk what i did wrong

**Expected behavior**
I expected it to start up and open the page in my browser

**Error**
``` (sd-inf) D:\toinfinity\andbeyond\stablediffusion-infinity-0.1.2>python app.py
Traceback (most recent call last):
  File "D:\toinfinity\andbeyond\stablediffusion-infinity-0.1.2\app.py", line 9, in <module>
    import diffusers
  File "C:\Users\clark\anaconda3\envs\sd-inf\lib\site-packages\diffusers\__init__.py", line 32, in <module>
    from .pipelines import (
  File "C:\Users\clark\anaconda3\envs\sd-inf\lib\site-packages\diffusers\pipelines\__init__.py", line 18, in <module>
    from .alt_diffusion import AltDiffusionImg2ImgPipeline, AltDiffusionPipeline
  File "C:\Users\clark\anaconda3\envs\sd-inf\lib\site-packages\diffusers\pipelines\alt_diffusion\__init__.py", line 33, in <module>
    from .pipeline_alt_diffusion import AltDiffusionPipeline
  File "C:\Users\clark\anaconda3\envs\sd-inf\lib\site-packages\diffusers\pipelines\alt_diffusion\pipeline_alt_diffusion.py", line 35, in <module>
    from ..stable_diffusion.safety_checker import StableDiffusionSafetyChecker
  File "C:\Users\clark\anaconda3\envs\sd-inf\lib\site-packages\diffusers\pipelines\stable_diffusion\__init__.py", line 33, in <module>
    from .pipeline_stable_diffusion_image_variation import StableDiffusionImageVariationPipeline
  File "C:\Users\clark\anaconda3\envs\sd-inf\lib\site-packages\diffusers\pipelines\stable_diffusion\pipeline_stable_diffusion_image_variation.py", line 22, in <module>
    from transformers import CLIPFeatureExtractor, CLIPVisionModelWithProjection
ImportError: cannot import name 'CLIPVisionModelWithProjection' from 'transformers' (C:\Users\clark\anaconda3\envs\sd-inf\lib\site-packages\transformers\__init__.py) ```

**Desktop (please complete the following information):**
-Win 10 
-I7-9700, RTX 2070 SUPER, 32gb ram
**Additional context**
i followed the installation guide, so idk what happened

**Comment by lkwq007** [comment]
https://github.com/huggingface/diffusers/releases/tag/v0.8.1
That's a upstream issue. You need to upgrade `diffusers` to the latest version.
