### ISSUE TITLE
[Bug] After SD2 integration update, I get a "TypeError: 'NoneType' object is not callable" when turning off the Safety Checker

### ISSUE THREAD

**Issue by RobZim41** [lkwq007/stablediffusion-infinity#153]
I tried loading the inpaint 2 model. Normal generations work great, but when I disable the Safety Checker, I get a "TypeError: 'NoneType' object is not callable" error. I tried switching back to the prior inpaint model, but am still getting the error.  

Here's the full output:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/gradio/routes.py", line 298, in run_predict
    iterators=iterators,
  File "/usr/local/lib/python3.7/dist-packages/gradio/blocks.py", line 1007, in process_api
    result = await self.call_function(fn_index, inputs, iterator, request)
  File "/usr/local/lib/python3.7/dist-packages/gradio/blocks.py", line 849, in call_function
    block_fn.fn, *processed_input, limiter=self.limiter
  File "/usr/local/lib/python3.7/dist-packages/anyio/to_thread.py", line 32, in run_sync
    func, *args, cancellable=cancellable, limiter=limiter
  File "/usr/local/lib/python3.7/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.7/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "app.py", line 826, in run_outpaint
    height=height,
  File "app.py", line 423, in run
    **extra_kwargs,
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py", line 730, in __call__
    image, has_nsfw_concept = self.run_safety_checker(image, device, text_embeddings.dtype)
  File "/usr/local/lib/python3.7/dist-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py", line 451, in run_safety_checker
    safety_checker_input = self.feature_extractor(self.numpy_to_pil(image), return_tensors="pt").to(device)
TypeError: 'NoneType' object is not callable
```

**Comment by RobZim41** [comment]
Just adding: if I reload Colab/Gradio from scratch and just load the prior inpaint model, everything works as before.

**Comment by lkwq007** [comment]
Seems that https://huggingface.co/stabilityai/stable-diffusion-2-inpainting `diffusers` version does not provide the model weight for safety checker and feature extractor. In that case, the safety checker is disabled by default.
