### ISSUE TITLE
File not found error on windows after paste huggingface login token

### ISSUE THREAD

**Issue by orangpelupa** [lkwq007/stablediffusion-infinity#17]
I've checked this guide https://github.com/lkwq007/stablediffusion-infinity/issues/12 but the error is different

```
        To login, `huggingface_hub` now requires a token generated from https://huggingface.co/settings/tokens .

Token:
Traceback (most recent call last):
  File "B:\tools\anaconda3\envs\sd-inf\Scripts\huggingface-cli-script.py", line 9, in <module>
    sys.exit(main())
  File "B:\tools\anaconda3\envs\sd-inf\lib\site-packages\huggingface_hub\commands\huggingface_cli.py", line 41, in main
    service.run()
  File "B:\tools\anaconda3\envs\sd-inf\lib\site-packages\huggingface_hub\commands\user.py", line 176, in run
    _login(self._api, token=token)
  File "B:\tools\anaconda3\envs\sd-inf\lib\site-packages\huggingface_hub\commands\user.py", line 344, in _login
    hf_api.set_access_token(token)
  File "B:\tools\anaconda3\envs\sd-inf\lib\site-packages\huggingface_hub\hf_api.py", line 705, in set_access_token
    write_to_credential_store(USERNAME_PLACEHOLDER, access_token)
  File "B:\tools\anaconda3\envs\sd-inf\lib\site-packages\huggingface_hub\hf_api.py", line 528, in write_to_credential_store
    with subprocess.Popen(
  File "B:\tools\anaconda3\envs\sd-inf\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "B:\tools\anaconda3\envs\sd-inf\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by Kim2091** [comment]
Interesting. You may still need to install the huggingface cli package with `pip install huggingface_hub` if you haven't. I didn't realize this could be an issue.

**Comment by mhartung** [comment]
> Interesting. You may still need to install the huggingface cli package with `pip install huggingface_hub` if you haven't. I didn't realize this could be an issue.

I am in with this error and the huggingface_hub is already installed.

**Comment by lkwq007** [comment]
The updated UI no longer needs `huggingface_hub login`, I'll close this issue.

**Comment by Dhananjay-prod** [comment]
Hey, I came across the same problem. Installed Huggingface using pip, the command huggingface-cli login keeps giving me the same error. How did you resolve this error?
