### ISSUE TITLE
[Bug] Error when using Photometric Correction on Windows install

### ISSUE THREAD

**Issue by mike4llison** [lkwq007/stablediffusion-infinity#60]
Everything was installed correctly there were no errors. Initially, it was working great then I toggled Photometric Correction and the prompt box was replaced by Error in red and un selectable. The only way to resume was to uncheck Photometric Correction and re-run the outpaint. Command line reported the following:

Traceback (most recent call last):
  File "C:\Users\mike4\.conda\envs\sd-inf\lib\site-packages\gradio\routes.py", line 275, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\mike4\.conda\envs\sd-inf\lib\site-packages\gradio\blocks.py", line 760, in process_api
    result = await self.call_function(fn_index, inputs, iterator)
  File "C:\Users\mike4\.conda\envs\sd-inf\lib\site-packages\gradio\blocks.py", line 671, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\mike\.conda\envs\sd-inf\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\mike4\.conda\envs\sd-inf\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\mike4\.conda\envs\sd-inf\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\mike4\stablediffusion-infinity\app.py", line 263, in run_outpaint
    image = Image.fromarray(image)
  File "C:\Users\mike4\.conda\envs\sd-inf\lib\site-packages\PIL\Image.py", line 2974, in fromarray
    return frombuffer(mode, size, obj, "raw", rawmode, 0, 1)
  File "C:\Users\mike4\.conda\envs\sd-inf\lib\site-packages\PIL\Image.py", line 2901, in frombuffer
    return frombytes(mode, size, data, decoder_name, args)
  File "C:\Users\mike4\.conda\envs\sd-inf\lib\site-packages\PIL\Image.py", line 2843, in frombytes
    im.frombytes(data, decoder_name, args)
  File "C:\Users\mike4\.conda\envs\sd-inf\lib\site-packages\PIL\Image.py", line 795, in frombytes
    s = d.decode(data)
TypeError: a bytes-like object is required, not 'Image'

I'm using Windows 11 in Chrome browser, Nvidia 2070 super.

I'm pretty new to Github though I haven't had any serious problems yet with installations.

**Comment by lkwq007** [comment]
Photometric correction only works with Linux/MacOS at present

**Comment by mike4llison** [comment]
Thanks for the reply, is there a roadmap for when there is going to be Windows implementation? I'm guessing not any time soon.
