### ISSUE TITLE
ImportError: cannot import name 'get_hf_file_metadata' from 'huggingface_hub'

### ISSUE THREAD

**Issue by ZeroCool22** [lkwq007/stablediffusion-infinity#68]
```
(sd-inf) zerocool@DESKTOP-IFR8E96:~/github/stablediffusion-infinity$ python app.py
Traceback (most recent call last):
  File "/home/zerocool/github/stablediffusion-infinity/app.py", line 9, in <module>
    import diffusers
  File "/home/zerocool/anaconda3/envs/sd-inf/lib/python3.10/site-packages/diffusers/__init__.py", line 32, in <module>
    from .pipelines import DDIMPipeline, DDPMPipeline, KarrasVePipeline, LDMPipeline, PNDMPipeline, ScoreSdeVePipeline
  File "/home/zerocool/anaconda3/envs/sd-inf/lib/python3.10/site-packages/diffusers/pipelines/__init__.py", line 15, in <module>
    from .latent_diffusion import LDMTextToImagePipeline
  File "/home/zerocool/anaconda3/envs/sd-inf/lib/python3.10/site-packages/diffusers/pipelines/latent_diffusion/__init__.py", line 6, in <module>
    from .pipeline_latent_diffusion import LDMBertModel, LDMTextToImagePipeline
  File "/home/zerocool/anaconda3/envs/sd-inf/lib/python3.10/site-packages/diffusers/pipelines/latent_diffusion/pipeline_latent_diffusion.py", line 8, in <module>
    from transformers.activations import ACT2FN
  File "/home/zerocool/anaconda3/envs/sd-inf/lib/python3.10/site-packages/transformers/__init__.py", line 30, in <module>
    from . import dependency_versions_check
  File "/home/zerocool/anaconda3/envs/sd-inf/lib/python3.10/site-packages/transformers/dependency_versions_check.py", line 17, in <module>
    from .utils.versions import require_version, require_version_core
  File "/home/zerocool/anaconda3/envs/sd-inf/lib/python3.10/site-packages/transformers/utils/__init__.py", line 48, in <module>
    from .hub import (
  File "/home/zerocool/anaconda3/envs/sd-inf/lib/python3.10/site-packages/transformers/utils/hub.py", line 32, in <module>
    from huggingface_hub import (
ImportError: cannot import name 'get_hf_file_metadata' from 'huggingface_hub' (/home/zerocool/anaconda3/envs/sd-inf/lib/python3.10/site-packages/huggingface_hub/__init__.py)
(sd-inf) zerocool@DESKTOP-IFR8E96:~/github/stablediffusion-infinity$
```

**Comment by ZeroCool22** [comment]
> conda update huggingface_hub -c conda-forge

Ok, but now:

![Screenshot_11](https://user-images.githubusercontent.com/13344308/195362429-4270242a-9d80-49cd-bd1d-2a49e71d7517.jpg)

**Comment by ZeroCool22** [comment]
@lkwq007 

Come on please help me. 
I just installed **WSL2 + Ubuntu** to have **patch match** and **Photometric Correction**....

**Comment by lkwq007** [comment]
> > conda update huggingface_hub -c conda-forge
> 
> Ok, but now:
> 
> ![Screenshot_11](https://user-images.githubusercontent.com/13344308/195362429-4270242a-9d80-49cd-bd1d-2a49e71d7517.jpg)


Seems that you need to install `build-essential` `cmake` and `libopencv-dev`. 
One potential issue is that latest version of `libopencv-dev` may provide `opencv4.pc` rather than `opencv.pc`, so 
in https://github.com/lkwq007/PyPatchMatch/blob/0ae9b8bbdc83f84214405376f13a2056568897fb/Makefile#L18 and https://github.com/lkwq007/PyPatchMatch/blob/0ae9b8bbdc83f84214405376f13a2056568897fb/Makefile#L20 ,
both `opencv` need to be replaced with `opencv4`
```
CXXFLAGS += $(shell pkg-config --cflags opencv) -fPIC
LDFLAGS = $(shell pkg-config --cflags --libs opencv) -shared -fPIC
```
