### ISSUE TITLE
Installing  fpie==0.2.3 fails.

### ISSUE THREAD

**Issue by ZeroCool22** [lkwq007/stablediffusion-infinity#69]
```
(sd-inf) zerocool@DESKTOP-IFR8E96:~/github/stablediffusion-infinity$ pip install fpie==0.2.3
Collecting fpie==0.2.3
  Using cached fpie-0.2.3.tar.gz (29 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: opencv-python>=4.5 in /home/zerocool/anaconda3/envs/sd-inf/lib/python3.10/site-packages (from fpie==0.2.3) (4.6.0.66)
Requirement already satisfied: numpy>=1.18 in /home/zerocool/anaconda3/envs/sd-inf/lib/python3.10/site-packages (from fpie==0.2.3) (1.22.3)
Requirement already satisfied: taichi>=1.0 in /home/zerocool/anaconda3/envs/sd-inf/lib/python3.10/site-packages (from fpie==0.2.3) (1.1.3)
Requirement already satisfied: numba>=0.51 in /home/zerocool/anaconda3/envs/sd-inf/lib/python3.10/site-packages (from fpie==0.2.3) (0.56.2)
Requirement already satisfied: setuptools<60 in /home/zerocool/anaconda3/envs/sd-inf/lib/python3.10/site-packages (from numba>=0.51->fpie==0.2.3) (59.8.0)
Requirement already satisfied: llvmlite<0.40,>=0.39.0dev0 in /home/zerocool/anaconda3/envs/sd-inf/lib/python3.10/site-packages (from numba>=0.51->fpie==0.2.3) (0.39.1)
Requirement already satisfied: colorama in /home/zerocool/anaconda3/envs/sd-inf/lib/python3.10/site-packages (from taichi>=1.0->fpie==0.2.3) (0.4.5)
Requirement already satisfied: sourceinspect>=0.0.4 in /home/zerocool/anaconda3/envs/sd-inf/lib/python3.10/site-packages (from taichi>=1.0->fpie==0.2.3) (0.0.4)
Requirement already satisfied: rich in /home/zerocool/anaconda3/envs/sd-inf/lib/python3.10/site-packages (from taichi>=1.0->fpie==0.2.3) (12.5.1)
Requirement already satisfied: dill in /home/zerocool/anaconda3/envs/sd-inf/lib/python3.10/site-packages (from sourceinspect>=0.0.4->taichi>=1.0->fpie==0.2.3) (0.3.5.1)
Requirement already satisfied: pygments<3.0.0,>=2.6.0 in /home/zerocool/anaconda3/envs/sd-inf/lib/python3.10/site-packages (from rich->taichi>=1.0->fpie==0.2.3) (2.13.0)
Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in /home/zerocool/anaconda3/envs/sd-inf/lib/python3.10/site-packages (from rich->taichi>=1.0->fpie==0.2.3) (0.9.1)
Building wheels for collected packages: fpie
  Building wheel for fpie (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [108 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.10
      creating build/lib.linux-x86_64-3.10/fpie
      copying fpie/numba_solver.py -> build/lib.linux-x86_64-3.10/fpie
      copying fpie/gui.py -> build/lib.linux-x86_64-3.10/fpie
      copying fpie/np_solver.py -> build/lib.linux-x86_64-3.10/fpie
      copying fpie/cli.py -> build/lib.linux-x86_64-3.10/fpie
      copying fpie/taichi_solver.py -> build/lib.linux-x86_64-3.10/fpie
      copying fpie/process.py -> build/lib.linux-x86_64-3.10/fpie
      copying fpie/args.py -> build/lib.linux-x86_64-3.10/fpie
      copying fpie/io.py -> build/lib.linux-x86_64-3.10/fpie
      copying fpie/__init__.py -> build/lib.linux-x86_64-3.10/fpie
      running build_ext
      -- The C compiler identification is GNU 9.4.0
      -- The CXX compiler identification is GNU 9.4.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Found Git: /usr/bin/git (found version "2.38.0")
      -- downloading/updating pybind11
      -- pybind11 directory not found, cloning...
      Cloning into '/tmp/pip-install-279hcf78/fpie_7f3ee7c52c254fa89c51937c7a6e6803/pybind11'...
      --
      Switched to a new branch 'stable'
      -- branch 'stable' set up to track 'origin/stable'.

      -- pybind11 v2.10.0
      -- Found PythonInterp: /home/zerocool/anaconda3/envs/sd-inf/bin/python (found suitable version "3.10.6", minimum required is "3.6")
      -- Found PythonLibs: /home/zerocool/anaconda3/envs/sd-inf/lib/libpython3.10.so
      -- Performing Test HAS_FLTO
      -- Performing Test HAS_FLTO - Success
      -- Found OpenMP_C: -fopenmp (found version "4.5")
      -- Found OpenMP_CXX: -fopenmp (found version "4.5")
      -- Found OpenMP: TRUE (found version "4.5")
      -- Found MPI_C: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so (found version "3.1")
      -- Found MPI_CXX: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so (found version "3.1")
      -- Found MPI: TRUE (found version "3.1")
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
      -- Looking for pthread_create in pthreads
      -- Looking for pthread_create in pthreads - not found
      -- Looking for pthread_create in pthread
      -- Looking for pthread_create in pthread - found
      -- Found Threads: TRUE
      -- Found CUDA: /usr/local/cuda (found version "11.7")
      -- The CUDA compiler identification is unknown
      CMake Error at /home/zerocool/anaconda3/envs/sd-inf/share/cmake-3.24/Modules/CMakeDetermineCUDACompiler.cmake:602 (message):
        Failed to detect a default CUDA architecture.



        Compiler output:

      Call Stack (most recent call first):
        fpie/core/cuda/CMakeLists.txt:2 (enable_language)


      -- Configuring incomplete, errors occurred!
      See also "/tmp/pip-install-279hcf78/fpie_7f3ee7c52c254fa89c51937c7a6e6803/build/temp.linux-x86_64-3.10/CMakeFiles/CMakeOutput.log".
      See also "/tmp/pip-install-279hcf78/fpie_7f3ee7c52c254fa89c51937c7a6e6803/build/temp.linux-x86_64-3.10/CMakeFiles/CMakeError.log".
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-279hcf78/fpie_7f3ee7c52c254fa89c51937c7a6e6803/setup.py", line 61, in <module>
          setup(
        File "/home/zerocool/anaconda3/envs/sd-inf/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/home/zerocool/anaconda3/envs/sd-inf/lib/python3.10/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/home/zerocool/anaconda3/envs/sd-inf/lib/python3.10/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/home/zerocool/anaconda3/envs/sd-inf/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/home/zerocool/anaconda3/envs/sd-inf/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/home/zerocool/anaconda3/envs/sd-inf/lib/python3.10/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/home/zerocool/anaconda3/envs/sd-inf/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/home/zerocool/anaconda3/envs/sd-inf/lib/python3.10/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/home/zerocool/anaconda3/envs/sd-inf/lib/python3.10/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/home/zerocool/anaconda3/envs/sd-inf/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/home/zerocool/anaconda3/envs/sd-inf/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 79, in run
          _build_ext.run(self)
        File "/home/zerocool/anaconda3/envs/sd-inf/lib/python3.10/distutils/command/build_ext.py", line 340, in run
          self.build_extensions()
        File "/home/zerocool/anaconda3/envs/sd-inf/lib/python3.10/distutils/command/build_ext.py", line 449, in build_extensions
          self._build_extensions_serial()
        File "/home/zerocool/anaconda3/envs/sd-inf/lib/python3.10/distutils/command/build_ext.py", line 474, in _build_extensions_serial
          self.build_extension(ext)
        File "/tmp/pip-install-279hcf78/fpie_7f3ee7c52c254fa89c51937c7a6e6803/setup.py", line 50, in build_extension
          subprocess.check_call(
        File "/home/zerocool/anaconda3/envs/sd-inf/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-install-279hcf78/fpie_7f3ee7c52c254fa89c51937c7a6e6803', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-279hcf78/fpie_7f3ee7c52c254fa89c51937c7a6e6803/build/lib.linux-x86_64-3.10/fpie/', '-DPYTHON_EXECUTABLE=/home/zerocool/anaconda3/envs/sd-inf/bin/python', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for fpie
  Running setup.py clean for fpie
Failed to build fpie
Installing collected packages: fpie
  Running setup.py install for fpie ... error
  error: subprocess-exited-with-error

  × Running setup.py install for fpie did not run successfully.
  │ exit code: 1
  ╰─> [104 lines of output]
      running install
      /home/zerocool/anaconda3/envs/sd-inf/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.10
      creating build/lib.linux-x86_64-3.10/fpie
      copying fpie/numba_solver.py -> build/lib.linux-x86_64-3.10/fpie
      copying fpie/gui.py -> build/lib.linux-x86_64-3.10/fpie
      copying fpie/np_solver.py -> build/lib.linux-x86_64-3.10/fpie
      copying fpie/cli.py -> build/lib.linux-x86_64-3.10/fpie
      copying fpie/taichi_solver.py -> build/lib.linux-x86_64-3.10/fpie
      copying fpie/process.py -> build/lib.linux-x86_64-3.10/fpie
      copying fpie/args.py -> build/lib.linux-x86_64-3.10/fpie
      copying fpie/io.py -> build/lib.linux-x86_64-3.10/fpie
      copying fpie/__init__.py -> build/lib.linux-x86_64-3.10/fpie
      running build_ext
      -- The C compiler identification is GNU 9.4.0
      -- The CXX compiler identification is GNU 9.4.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- pybind11 v2.10.0
      -- Found PythonInterp: /home/zerocool/anaconda3/envs/sd-inf/bin/python (found suitable version "3.10.6", minimum required is "3.6")
      -- Found PythonLibs: /home/zerocool/anaconda3/envs/sd-inf/lib/libpython3.10.so
      -- Performing Test HAS_FLTO
      -- Performing Test HAS_FLTO - Success
      -- Found OpenMP_C: -fopenmp (found version "4.5")
      -- Found OpenMP_CXX: -fopenmp (found version "4.5")
      -- Found OpenMP: TRUE (found version "4.5")
      -- Found MPI_C: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so (found version "3.1")
      -- Found MPI_CXX: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so (found version "3.1")
      -- Found MPI: TRUE (found version "3.1")
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
      -- Looking for pthread_create in pthreads
      -- Looking for pthread_create in pthreads - not found
      -- Looking for pthread_create in pthread
      -- Looking for pthread_create in pthread - found
      -- Found Threads: TRUE
      -- Found CUDA: /usr/local/cuda (found version "11.7")
      -- The CUDA compiler identification is unknown
      CMake Error at /home/zerocool/anaconda3/envs/sd-inf/share/cmake-3.24/Modules/CMakeDetermineCUDACompiler.cmake:602 (message):
        Failed to detect a default CUDA architecture.



        Compiler output:

      Call Stack (most recent call first):
        fpie/core/cuda/CMakeLists.txt:2 (enable_language)


      -- Configuring incomplete, errors occurred!
      See also "/tmp/pip-install-279hcf78/fpie_7f3ee7c52c254fa89c51937c7a6e6803/build/temp.linux-x86_64-3.10/CMakeFiles/CMakeOutput.log".
      See also "/tmp/pip-install-279hcf78/fpie_7f3ee7c52c254fa89c51937c7a6e6803/build/temp.linux-x86_64-3.10/CMakeFiles/CMakeError.log".
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-279hcf78/fpie_7f3ee7c52c254fa89c51937c7a6e6803/setup.py", line 61, in <module>
          setup(
        File "/home/zerocool/anaconda3/envs/sd-inf/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/home/zerocool/anaconda3/envs/sd-inf/lib/python3.10/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/home/zerocool/anaconda3/envs/sd-inf/lib/python3.10/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/home/zerocool/anaconda3/envs/sd-inf/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/home/zerocool/anaconda3/envs/sd-inf/lib/python3.10/site-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
        File "/home/zerocool/anaconda3/envs/sd-inf/lib/python3.10/distutils/command/install.py", line 568, in run
          self.run_command('build')
        File "/home/zerocool/anaconda3/envs/sd-inf/lib/python3.10/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/home/zerocool/anaconda3/envs/sd-inf/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/home/zerocool/anaconda3/envs/sd-inf/lib/python3.10/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/home/zerocool/anaconda3/envs/sd-inf/lib/python3.10/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/home/zerocool/anaconda3/envs/sd-inf/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/home/zerocool/anaconda3/envs/sd-inf/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 79, in run
          _build_ext.run(self)
        File "/home/zerocool/anaconda3/envs/sd-inf/lib/python3.10/distutils/command/build_ext.py", line 340, in run
          self.build_extensions()
        File "/home/zerocool/anaconda3/envs/sd-inf/lib/python3.10/distutils/command/build_ext.py", line 449, in build_extensions
          self._build_extensions_serial()
        File "/home/zerocool/anaconda3/envs/sd-inf/lib/python3.10/distutils/command/build_ext.py", line 474, in _build_extensions_serial
          self.build_extension(ext)
        File "/tmp/pip-install-279hcf78/fpie_7f3ee7c52c254fa89c51937c7a6e6803/setup.py", line 50, in build_extension
          subprocess.check_call(
        File "/home/zerocool/anaconda3/envs/sd-inf/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-install-279hcf78/fpie_7f3ee7c52c254fa89c51937c7a6e6803', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-279hcf78/fpie_7f3ee7c52c254fa89c51937c7a6e6803/build/lib.linux-x86_64-3.10/fpie/', '-DPYTHON_EXECUTABLE=/home/zerocool/anaconda3/envs/sd-inf/bin/python', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> fpie

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
(sd-inf) zerocool@DESKTOP-IFR8E96:~/github/stablediffusion-infinity$
```

**Comment by lkwq007** [comment]
Hi, as I have mentioned in https://github.com/lkwq007/stablediffusion-infinity/issues/64, I am not the maintainer of `fpie`. So I am unfamiliar with installation-related issues for `fpie`. Besides, I think the error might be related to your wsl cuda installation (related: https://learn.microsoft.com/en-us/windows/ai/directml/gpu-cuda-in-wsl). I am also unfamiliar with that.  Sorry I cannot help. 

By the way, perhaps you can use docker to avoid all these configurations.

**Comment by ZeroCool22** [comment]
> Hi, as I have mentioned in #64, I am not the maintainer of `fpie`. So I am unfamiliar with installation-related issues for `fpie`. Besides, I think the error might be related to your wsl cuda installation (related: https://learn.microsoft.com/en-us/windows/ai/directml/gpu-cuda-in-wsl). I am also unfamiliar with that. Sorry I cannot help.
> 
> By the way, perhaps you can use docker to avoid all these configurations.

But using the Docker method,  i will get **patchmatch** and the **photocorrection**?

**Comment by lkwq007** [comment]
> > Hi, as I have mentioned in #64, I am not the maintainer of `fpie`. So I am unfamiliar with installation-related issues for `fpie`. Besides, I think the error might be related to your wsl cuda installation (related: https://learn.microsoft.com/en-us/windows/ai/directml/gpu-cuda-in-wsl). I am also unfamiliar with that. Sorry I cannot help.
> > By the way, perhaps you can use docker to avoid all these configurations.
> 
> But using the Docker method, i will get **patchmatch** and the **photocorrection**?

Right, I think all these features are available with docker.

**Comment by urbanscribe** [comment]
Same issue here.  

Since the version is provided (fpie==0.2.3) not seeing why maintenance of the library would be an issue.  If skipped do we loose a core functionality?

**Comment by Trinkle23897** [comment]
released fpie==0.2.4 and it can install on win/mac/linux

**Comment by ZeroCool22** [comment]
> > > Hi, as I have mentioned in #64, I am not the maintainer of `fpie`. So I am unfamiliar with installation-related issues for `fpie`. Besides, I think the error might be related to your wsl cuda installation (related: https://learn.microsoft.com/en-us/windows/ai/directml/gpu-cuda-in-wsl). I am also unfamiliar with that. Sorry I cannot help.
> > > By the way, perhaps you can use docker to avoid all these configurations.
> > 
> > 
> > But using the Docker method, i will get **patchmatch** and the **photocorrection**?
> 
> Right, I think all these features are available with docker.


https://user-images.githubusercontent.com/13344308/195735511-59d42cf3-22db-442b-8e8e-d5891460860c.mp4

**Comment by ZeroCool22** [comment]
> released fpie==0.2.4 and it can install on win/mac/linux

![Screenshot_8](https://user-images.githubusercontent.com/13344308/195738161-45488c15-e18f-49d1-9e5f-7df5d7104880.jpg)


Finally worked, thx!

@lkwq007 

But when try to use **Photometric Correction** gives error, even with the new FPIE installed correctly:

![Screenshot_9](https://user-images.githubusercontent.com/13344308/195738406-42dfa4de-c6c6-4751-a8e7-68d4d2f8e1cf.jpg)

**Comment by Trinkle23897** [comment]
try uninstall taichi

**Comment by ZeroCool22** [comment]
> try uninstall taichi (it will switch default backend to numpy)

Can you tell me the correct command line to uninstall it, please?
 i'm new at linux. **(using WSL2 +Ubuntu)**

**Comment by Trinkle23897** [comment]
pip uninstall taichi

**Comment by Trinkle23897** [comment]
yes

**Comment by ZeroCool22** [comment]
> pip uninstall taichi

Great working now!

![xxxxxx](https://user-images.githubusercontent.com/13344308/195739557-a0e38228-8032-4aa2-a6be-ea16e8722e44.png)

I only see the error: **PIE: Iter 5000, abs error [112.39817 148.23424 149.15575]**

Don't know what that means and if  i can just ignore that....

**Comment by ZeroCool22** [comment]
> > pip uninstall taichi
> 
> Great working now!
> 
> ![xxxxxx](https://user-images.githubusercontent.com/13344308/195739557-a0e38228-8032-4aa2-a6be-ea16e8722e44.png)
> 
> I only see the error: **PIE: Iter 5000, abs error [112.39817 148.23424 149.15575]**
> 
> Don't know what that means and if i can just ignore that....



> > pip uninstall taichi
> 
> **Great, working now!**
> 
> ![Screenshot_11](https://user-images.githubusercontent.com/13344308/195739866-d41fb741-f689-4118-a20e-42d676582ba8.jpg)
> 
> ![xxxxxx](https://user-images.githubusercontent.com/13344308/195739557-a0e38228-8032-4aa2-a6be-ea16e8722e44.png)
> 
> I only see the error: **PIE: Iter 5000, abs error [112.39817 148.23424 149.15575]**
> 
> Don't know what that means and if i can just ignore that....

**Comment by lkwq007** [comment]
> released fpie==0.2.4 and it can install on win/mac/linux

Thanks for releasing that. 

> try uninstall taichi (it will switch default backend to numpy), or set backend manually.
> 
> My guess is @lkwq007 does some shallow-copy on some array

Not sure about that. Photometric correction with `fpie`'s `taichi-cpu` backend works well on a Linux PC. 
Anyway, I'll check it later.

**Comment by Trinkle23897** [comment]
@lkwq007 can you upgrade the dependency to fpie==0.2.4?

**Comment by gateway** [comment]
Im having an issue running this on windows 10 with conda env.. I tried fpie==0.2.4 but that failed as well.  Will this not run natively on windows/conda env?  @Trinkle23897 .. cheers..

**Comment by Trinkle23897** [comment]
Try `pip install git+https://github.com/Trinkle23897/Fast-Poisson-Image-Editing.git`

**Comment by gateway** [comment]
@Trinkle23897 since your replying to these.. any ideas now why I would get this when I enable mask_mode or border_mode

```[W 11/08/22 14:18:18.513 24912] [C:/Users/Administrator/actions-runner/_work/taichi/taichi/taichi/transforms/offload.cpp:emit_struct_for@236] Specified block dim 1024 is bigger than SNode element size 64. Clipping.
[PIE] not working, photometric correction is disabled```

:/ grrr :)

**Comment by Trinkle23897** [comment]
I don't know... maybe you can switch to another backend like numba. The simplest way is to `pip uninstall taichi` which will change the default backend from taichi to numba

**Comment by ernietedeschi** [comment]
For either @Trinkle23897 or @lkwq007:

When running sd-inf, is there a way to force `fpie` to use the `taichi-gpu` backend? It keeps using `taich-cpu` which is slow on my installation (Windows 11, RTX 3060).

**Comment by Trinkle23897** [comment]
You need to set fpie's solver backend to `taichi-gpu` somewhere: https://github.com/Trinkle23897/Fast-Poisson-Image-Editing/blob/6a607f17e335a8be97cbfe39dd9b2de6de2a7cb6/fpie/process.py#L20-L25

**Comment by ernietedeschi** [comment]
Thanks!

So, I modified `process.py` not only so that `DEFAULT_BACKEND = "taichi-gpu"` but so that `"taichi-cpu"` was not even included in the `ALL_BACKEND` vector at all. Running with the `--check-backend` option, it ostensibly seems to work:

![image](https://user-images.githubusercontent.com/3980178/216859878-dee3cfc0-e0ef-40a5-9f7d-f5a0fb14ed6c.png)

I also modified `taichi_solver.py` so that any call of `ti_init()` hard-codes the `arch=ti.gpu` option.

But then here's the weird thing: I run sd-inf, but it still tells me the backend is `taichi-cpu`! This makes me worry that it's defaulting to the CPU backend somewhere else and trying to pass a CPU count argument when a block size argument is expected.

![image](https://user-images.githubusercontent.com/3980178/216860879-659faa6c-fe41-4ccc-9b82-71a0f3e778b4.png)

(And no, photometric mode doesn't work at all with this setup, I get the same error I did before under the `taichi-cpu` backend.)

**Comment by Trinkle23897** [comment]
Can you check which PIE is used for sd-inf? I guess it's somewhere like `~/.local/lib/python3.8/site-packages/fpie/xxx` (in linux), but you modify the local version instead of installed version

**Comment by lkwq007** [comment]
> Thanks!
> 
> So, I modified `process.py` not only so that `DEFAULT_BACKEND = "taichi-gpu"` but so that `"taichi-cpu"` was not even included in the `ALL_BACKEND` vector at all. Running with the `--check-backend` option, it ostensibly seems to work:
> 
> ![image](https://user-images.githubusercontent.com/3980178/216859878-dee3cfc0-e0ef-40a5-9f7d-f5a0fb14ed6c.png)
> 
> I also modified `taichi_solver.py` so that any call of `ti_init()` hard-codes the `arch=ti.gpu` option.
> 
> But then here's the weird thing: I run sd-inf, but it still tells me the backend is `taichi-cpu`! This makes me worry that it's defaulting to the CPU backend somewhere else and trying to pass a CPU count argument when a block size argument is expected.
> 
> ![image](https://user-images.githubusercontent.com/3980178/216860879-659faa6c-fe41-4ccc-9b82-71a0f3e778b4.png)
> 
> (And no, photometric mode doesn't work at all with this setup, I get the same error I did before under the `taichi-cpu` backend.)

You need to modify this file https://github.com/lkwq007/stablediffusion-infinity/blob/master/process.py#L49

**Comment by ernietedeschi** [comment]
> You need to modify this file https://github.com/lkwq007/stablediffusion-infinity/blob/master/process.py#L49

That perfectly addressed the issue I raised, thank you. Unfortunately, I'm still getting the `[PIE] not working, photometric correction is disabled` error even with `taichi-gpu`, so back to square one for me.
