### ISSUE TITLE
[Bug] NameError: name 'functbl' is not defined

### ISSUE THREAD

**Issue by ZeroCool22** [lkwq007/stablediffusion-infinity#96]
```
Traceback (most recent call last):
  File "/home/zerocool/anaconda3/envs/sd-inf/lib/python3.10/site-packages/gradio/routes.py", line 275, in run_predict
    output = await app.blocks.process_api(
  File "/home/zerocool/anaconda3/envs/sd-inf/lib/python3.10/site-packages/gradio/blocks.py", line 760, in process_api
    result = await self.call_function(fn_index, inputs, iterator)
  File "/home/zerocool/anaconda3/envs/sd-inf/lib/python3.10/site-packages/gradio/blocks.py", line 671, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/zerocool/anaconda3/envs/sd-inf/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/zerocool/anaconda3/envs/sd-inf/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/zerocool/anaconda3/envs/sd-inf/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/zerocool/github/stablediffusion-infinity/utils.py", line 716, in run_outpaint
    images = cur_model.run(
  File "/home/zerocool/github/stablediffusion-infinity/utils.py", line 624, in run
    img, mask = functbl[fill_mode](img, mask)
NameError: name 'functbl' is not defined
```

![cf2009c62d0e6946b64ddb5460192e4e](https://user-images.githubusercontent.com/13344308/197364392-17a3e1cb-3c93-4aa0-92e9-ae0da338fa5a.gif)

**Comment by lkwq007** [comment]
Could you please elaborate the steps to reproduce the mentioned issue?

**Comment by ZeroCool22** [comment]
> Could you please elaborate the steps to reproduce the mentioned issue?

Here you have it:

https://user-images.githubusercontent.com/13344308/197410780-9480a664-d0aa-4c52-a4b7-1537771ed053.mp4

**Comment by ZeroCool22** [comment]
**UPDATE:**

With the last PULL now it's working.
